name: "Mys"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run sign
        run: |
          pip install requests==2.20.0
          python3 ./v2freeClockin.py --username "${{ secrets.V2FREE_USER }}" --password "${{ secrets.V2FREE_PWD }}"
